# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 11:40
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_awards', '0002_auto_20190524_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_post',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
