# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_awards', '0003_projects_project_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_post',
        ),
    ]
