# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_awards', '0004_remove_projects_project_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
