# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-25 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_awards', '0005_auto_20190524_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
